# -*- coding: utf-8 -*-
"""FACTORIAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q9wtTYZiBB3ZMRxZcU-DA5DiSLyMizWK
"""

n=5
fact=1
for i in range(1,n+1):
  fact=fact*i
print("Factorial of",n,"=", fact)